//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;


namespace Osmium.Engine {
	
	partial class SystemSymbols {
		
					public Symbol Symbol { get; }
					public Symbol List { get; }
					public Symbol Blank { get; }
					public Symbol BlankSequence { get; }
					public Symbol BlankNullSequence { get; }
					public Symbol Pattern { get; }
					public Symbol Sequence { get; }
					public Symbol Set { get; }
					public Symbol SetDelayed { get; }
					public Symbol Null { get; }
		
		public SystemSymbols(OsmiumEngine e) {
							Symbol = e.GetSymbol("System`", "Symbol");
							List = e.GetSymbol("System`", "List");
							Blank = e.GetSymbol("System`", "Blank");
							BlankSequence = e.GetSymbol("System`", "BlankSequence");
							BlankNullSequence = e.GetSymbol("System`", "BlankNullSequence");
							Pattern = e.GetSymbol("System`", "Pattern");
							Sequence = e.GetSymbol("System`", "Sequence");
							Set = e.GetSymbol("System`", "Set");
							SetDelayed = e.GetSymbol("System`", "SetDelayed");
							Null = e.GetSymbol("System`", "Null");
			
			Init();
		}
	}
}