//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;


namespace Osmium.Engine {
	
	partial class SystemSymbols {
		
					public Symbol All { get; }
					public Symbol And { get; }
					public Symbol Append { get; }
					public Symbol Apply { get; }
					public Symbol True { get; }
					public Symbol False { get; }
					public Symbol Symbol { get; }
					public Symbol List { get; }
					public Symbol Blank { get; }
					public Symbol BlankSequence { get; }
					public Symbol BlankNullSequence { get; }
					public Symbol Pattern { get; }
					public Symbol Sequence { get; }
					public Symbol Set { get; }
					public Symbol SetDelayed { get; }
					public Symbol Null { get; }
					public Symbol String { get; }
					public Symbol Integer { get; }
					public Symbol Real { get; }
					public Symbol Rational { get; }
					public Symbol Complex { get; }
		
		public SystemSymbols(OsmiumEngine e) {
							All = e.GetSymbol("System`", "All");
							And = e.GetSymbol("System`", "And");
							Append = e.GetSymbol("System`", "Append");
							Apply = e.GetSymbol("System`", "Apply");
							True = e.GetSymbol("System`", "True");
							False = e.GetSymbol("System`", "False");
							Symbol = e.GetSymbol("System`", "Symbol");
							List = e.GetSymbol("System`", "List");
							Blank = e.GetSymbol("System`", "Blank");
							BlankSequence = e.GetSymbol("System`", "BlankSequence");
							BlankNullSequence = e.GetSymbol("System`", "BlankNullSequence");
							Pattern = e.GetSymbol("System`", "Pattern");
							Sequence = e.GetSymbol("System`", "Sequence");
							Set = e.GetSymbol("System`", "Set");
							SetDelayed = e.GetSymbol("System`", "SetDelayed");
							Null = e.GetSymbol("System`", "Null");
							String = e.GetSymbol("System`", "String");
							Integer = e.GetSymbol("System`", "Integer");
							Real = e.GetSymbol("System`", "Real");
							Rational = e.GetSymbol("System`", "Rational");
							Complex = e.GetSymbol("System`", "Complex");
			
			Init();
		}
	}
}